/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package game;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test
    public void dontLoseGame() {
        App app = new App();
        assertFalse("Game is not lost", app.isGameLost());
    }

    @Test
    public void doLoseGame() {
        App app = new App();
        for (int i = 0; i < 10; i++) {
            app.guessLetter('z');
        }
        assertTrue("Game is lost", app.isGameLost());
    }
}
