/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package price_display;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test public void getPriceLabel() {
        App classUnderTest = new App();
        assertEquals("A banana costs 50", String.valueOf("The price for item: banana is 50"), classUnderTest.getPriceLabel("banana", 50));
    }
}
