/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package get_price_label;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }

    public String getPriceLabel(String item, Double price) {
        return "The price for the item: " + item + " is " + price;
    }
}
