/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package get_price_label;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test public void appDisplaysItemWithPrice() {
        App classUnderTest = new App();
        assertEquals("app should return item along wth price", String.valueOf("The price for the item: Teapot is 10.99"), classUnderTest.getPriceLabel("Teapot", 10.99));
    }
}
